query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query homeQuery {
  ...LayoutQueryFragment
  home(relativePath: "index.json") {
    ...HomeParts
  }
}
